name: Feign Mock - Publish snapshot
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Java SDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
          cache: 'gradle'
      - name: Build
        run: ./gradlew build publish --stacktrace
        env:
          GITHUB_USER: ${{secrets.CICD_TOKEN_USERNAME}}
          GITHUB_TOKEN: ${{secrets.CICD_TOKEN_KEY}}
      - name: 'Publish Test Report'
        if: always()
        uses: actions/upload-artifact@v2-preview
        with:
          name: 'test-report'
          path: build/reports/tests/test/*
      - name: Test Summary
        uses: test-summary/action@v2
        with:
          paths: "build/test-results/**/TEST-*.xml"
        if: always()
